<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '847c078058e558ea82411d162b67c4bb',
  'DATABASE_URL' => 'mysql://wydcazcimp:kigu7waWR5gJDNq@wydcazcimp.mysql.db/wydcazcimp',
);
